name: ะก++ division by zero validation

on:
  push:
    branches: [ "master" ]
    paths:
      - examples/**
  pull_request:
    branches: [ "master" ]
    paths:
      - examples/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Validate
      run: bash examples/run.sh examples/div-by-zero.c
    - name: Upload results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: polystat-eo-out
        path: polystat-eo-out.txt
